version: '3.8'

services:
  domjudge-web:
    image: domjudge/domserver:8.1.3
    container_name: domserver
    depends_on:
      - domjudge-db
    env_file:
      - domserver.env
    ports:
      - "12345:80"
      
  domjudge-db:
    image: mariadb:latest
    container_name: domjudge-db
    env_file:
      - domserver.env
    volumes:
      - ./db:/var/lib/mysql

